license: Viri_Loves_Me

# How many threads should NordVPN run at?
threads: 1000

# If the proxy is banned, how many times should the checker re-try with another proxy?
retries: 10

show_only_hits: false

proxy_type: http

# milliseconds (1000 milliseconds: 1 second)
proxy_timeout: 25000
    
# Proxy Api Url
# Leave empty or comment value if you want to use proxies file
proxy_url: 

# Time to refresh the proxies using API in milliseconds if you are using proxy api
proxy_refresh: 10000
